/* Generated by camel build tools - do NOT edit this file! */
package es.omarall.camel.components.videoio;

import java.util.Map;

import org.apache.camel.CamelContext;
import org.apache.camel.spi.ExtendedPropertyConfigurerGetter;
import org.apache.camel.spi.PropertyConfigurerGetter;
import org.apache.camel.spi.ConfigurerStrategy;
import org.apache.camel.spi.GeneratedPropertyConfigurer;
import org.apache.camel.util.CaseInsensitiveMap;
import org.apache.camel.support.component.PropertyConfigurerSupport;

/**
 * Generated by camel build tools - do NOT edit this file!
 */
@SuppressWarnings("unchecked")
public class VideoIOEndpointConfigurer extends PropertyConfigurerSupport implements GeneratedPropertyConfigurer, PropertyConfigurerGetter {

    @Override
    public boolean configure(CamelContext camelContext, Object obj, String name, Object value, boolean ignoreCase) {
        VideoIOEndpoint target = (VideoIOEndpoint) obj;
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "analysisquality":
        case "analysisQuality": target.getConfiguration().setAnalysisQuality(property(camelContext, java.lang.String.class, value)); return true;
        case "bridgeerrorhandler":
        case "bridgeErrorHandler": target.setBridgeErrorHandler(property(camelContext, boolean.class, value)); return true;
        case "captureaddress":
        case "captureAddress": target.getConfiguration().setCaptureAddress(property(camelContext, java.lang.String.class, value)); return true;
        case "exceptionhandler":
        case "exceptionHandler": target.setExceptionHandler(property(camelContext, org.apache.camel.spi.ExceptionHandler.class, value)); return true;
        case "exchangepattern":
        case "exchangePattern": target.setExchangePattern(property(camelContext, org.apache.camel.ExchangePattern.class, value)); return true;
        case "frameheight":
        case "frameHeight": target.getConfiguration().setFrameHeight(property(camelContext, java.lang.Integer.class, value)); return true;
        case "framerate":
        case "frameRate": target.getConfiguration().setFrameRate(property(camelContext, java.lang.Double.class, value)); return true;
        case "framewidth":
        case "frameWidth": target.getConfiguration().setFrameWidth(property(camelContext, java.lang.Integer.class, value)); return true;
        case "lazystartproducer":
        case "lazyStartProducer": target.setLazyStartProducer(property(camelContext, boolean.class, value)); return true;
        default: return false;
        }
    }

    @Override
    public Class<?> getOptionType(String name, boolean ignoreCase) {
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "analysisquality":
        case "analysisQuality": return java.lang.String.class;
        case "bridgeerrorhandler":
        case "bridgeErrorHandler": return boolean.class;
        case "captureaddress":
        case "captureAddress": return java.lang.String.class;
        case "exceptionhandler":
        case "exceptionHandler": return org.apache.camel.spi.ExceptionHandler.class;
        case "exchangepattern":
        case "exchangePattern": return org.apache.camel.ExchangePattern.class;
        case "frameheight":
        case "frameHeight": return java.lang.Integer.class;
        case "framerate":
        case "frameRate": return java.lang.Double.class;
        case "framewidth":
        case "frameWidth": return java.lang.Integer.class;
        case "lazystartproducer":
        case "lazyStartProducer": return boolean.class;
        default: return null;
        }
    }

    @Override
    public Object getOptionValue(Object obj, String name, boolean ignoreCase) {
        VideoIOEndpoint target = (VideoIOEndpoint) obj;
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "analysisquality":
        case "analysisQuality": return target.getConfiguration().getAnalysisQuality();
        case "bridgeerrorhandler":
        case "bridgeErrorHandler": return target.isBridgeErrorHandler();
        case "captureaddress":
        case "captureAddress": return target.getConfiguration().getCaptureAddress();
        case "exceptionhandler":
        case "exceptionHandler": return target.getExceptionHandler();
        case "exchangepattern":
        case "exchangePattern": return target.getExchangePattern();
        case "frameheight":
        case "frameHeight": return target.getConfiguration().getFrameHeight();
        case "framerate":
        case "frameRate": return target.getConfiguration().getFrameRate();
        case "framewidth":
        case "frameWidth": return target.getConfiguration().getFrameWidth();
        case "lazystartproducer":
        case "lazyStartProducer": return target.isLazyStartProducer();
        default: return null;
        }
    }
}

